name: gee
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy
  - pandas
  - scipy
  - matplotlib
  - ipywidgets
  - pymannkendall
  - geopandas
  - seaborn
  - scikit-learn
  - jsonschema  # Needed for `json` related operations, generally available in base packages.
  - pip

